name: CI Pipeline  
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [ opened, synchronize ]  
  
jobs:  
  ci-pipeline:  
    runs-on: ubuntu-latest  
    strategy:
        matrix: 
          python-version: ["3.10"]
    steps:  
      - name: Checkout  
        uses: actions/checkout@v2  
      - name: Setup Python  
        uses: actions/setup-python@v2  
        with:  
          python-version: 3.10.0  
          architecture: x64  
          cache: 'pip'  
      - name: Installing dependencies
        run: |
          pip install -r 'src/requirements.txt'
      - name: Create lock file 
        run: |
          pipenv install
          pipenv lock
      - name: Run flake  
        run: flake8 --ignore=E111,E231,E275,E302,E501,E703,F403,F405,W191,W291,W293
