name: CI Pipeline  
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [ opened, synchronize ]  
  
jobs:  
  ci-pipeline:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout  
        uses: actions/checkout@v2  
      - name: Setup Python  
        uses: actions/setup-python@v2  
        with:  
          python-version: 3.10.0  
          architecture: x64  
          cache: 'pip'  
      - name: Installing dependencies
        run: |
          pip install -r 'src/requirements.txt'
      - name: Run pipenv 
        run: pipenv install
      - name: Run pytest  
        run: pytest -vs tests/test_instances.py
