name: Python

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PYTEST_ADDOPTS: "--color=yes"
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix: 
          python-version: ["3.10"]
          include:
            - name: "windows-py310"
              python: "3.10"
              os: windows-latest
              tox_env: "py310-xdist"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Python ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install tox coverage
          pip install --upgrade pip
          pip install -r 'src/requirements.txt'
          pip install pytest
          pip install flake8
      - name: Testing stuff with the flake 8 module 
        run: |
          flake8 .
        continue-on-error: true
      
